## "create one R script called run_analysis.R that does the following":

setwd("../Desktop")
#download.file(
#"http://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip",
#"foo.zip")
#unzip('foo.zip')

# 1. Merges the training and the test sets to create one data set.
library(data.table)
dtSubjectTrain	<- fread("UCI HAR Dataset/train/subject_train.txt")
dtSubjectTest	<- fread("UCI HAR Dataset/test/subject_test.txt")
dtActivityTrain	<- fread("UCI HAR Dataset/train/y_train.txt")
dtActivityTest	<- fread("UCI HAR Dataset/test/y_test.txt")
x			<- read.table("UCI HAR Dataset/train/X_train.txt")
dtTrain		<- data.table(x)
x			<- read.table("UCI HAR Dataset/test/X_test.txt")
dtTest		<- data.table(x)
dtSubject		<- rbind(dtSubjectTrain, dtSubjectTest)
setnames(dtSubject, "V1", "subject")
dtActivity		<- rbind(dtActivityTrain, dtActivityTest)
setnames(dtActivity, "V1", "activityNum")
dt			<- rbind(dtTrain, dtTest)
dtSubject		<- cbind(dtSubject, dtActivity)
dt			<- cbind(dtSubject, dt)
setkey(dt, subject, activityNum)

# 2. Extracts only the measurements on the mean and SD for each measurement.
dtFeatures	<- fread("UCI HAR Dataset/features.txt")
setnames(dtFeatures, names(dtFeatures), c("featureNum", "featureName"))
dtFeatures	<- dtFeatures[grepl("mean\\(\\)|std\\(\\)", featureName)]
dtFeatures$featureCode <- dtFeatures[, paste0("V", featureNum)]
select	<- c(key(dt), dtFeatures$featureCode)
dt		<- dt[, select, with=F]

# 3. Uses descriptive activity names to name the activities in the data set.
dtActivityNames <- fread("UCI HAR Dataset/activity_labels.txt")
setnames(dtActivityNames, names(dtActivityNames), c("activityNum", "activityName"))

# 4. Appropriately labels the data set with descriptive activity names.
dt		<- merge(dt, dtActivityNames, by="activityNum", all.x=T)
setkey(dt, subject, activityNum, activityName)
library(reshape2)
dt		<- data.table(melt(dt, key(dt), variable.name="featureCode"))
dt		<- merge(dt, dtFeatures[, list(featureNum, featureCode, featureName)],
			by="featureCode", all.x=T)
dt$activity	<- factor(dt$activityName)
dt$feature	<- factor(dt$featureName)

GrepCanSuck <- function (regex) {grepl(regex, dt$feature)}
n <- 2;y <- matrix(seq(1, n), nrow=n)
x <- matrix(c(GrepCanSuck("^t"), GrepCanSuck("^f")), ncol=nrow(y))
dt$DomainF <- factor(x %*% y, labels=c("Time", "Freq"))
x <- matrix(c(GrepCanSuck("Acc"), GrepCanSuck("Gyro")), ncol=nrow(y))
dt$InstrumentF <- factor(x %*% y, labels=c("Accelerometer", "Gyroscope"))
x <- matrix(c(GrepCanSuck("BodyAcc"), GrepCanSuck("GravityAcc")), ncol=nrow(y))
dt$AccelerationF <- factor(x %*% y, labels=c(NA, "Body", "Gravity"))
x <- matrix(c(GrepCanSuck("mean()"), GrepCanSuck("std()")), ncol=nrow(y))
dt$VariableF <- factor(x %*% y, labels=c("Mean", "SD"))
dt$JerkF <- factor(GrepCanSuck("Jerk"), labels=c(NA, "Jerk"))
dt$MagnitudeF <- factor(GrepCanSuck("Mag"), labels=c(NA, "Magnitude"))
n <- 3; y <- matrix(seq(1, n), nrow=n)
x <- matrix(c(GrepCanSuck("-X"), GrepCanSuck("-Y"), GrepCanSuck("-Z")), ncol=nrow(y))
dt$AxisF <- factor(x %*% y, labels=c(NA, "X", "Y", "Z"))

# 5. Creates a second, independent tidy data set with the average of each
#	variable for each activity and each subject.
setkey(dt, subject, activity, DomainF, AccelerationF, InstrumentF,
	JerkF, MagnitudeF, VariableF, AxisF)
dtTidy <- dt[, list(count = .N, average = mean(value)), by=key(dt)]
write.table(dtTidy, "Tidy.txt", quote=F, sep="\t", row.names=F)

# make CodeBook.html
library(knitr)
foo <- file('CodeBook.md')
writeLines("
Codebook
========
Codebook generated by run_analyis.R during tidy data set generation.

# Variables

## Name: Definition  
Acceleration: *Body vs gravity acceleration signal*  
Activity: *Name of activity*  
Average: *Average of each variable for each activity and each subject*  
Axis: *X, Y and Z 3-axial signal direction*  
Count: *Num data points*  
Domain: *Domain signals frequency vs time*  
Instrument: *The instrument used, either accelerometer or gyroscope*  
Jerk: *Instrument jerk sig*  
Magnitude: *From jerk signal, the calculated magnitude*  
Subject: *Participant ID for window samples*  
Variable: *Mean vs standard deviation*  

## Summary call
```{r}
summary(dtTidy)
```

## Structure call
```{r}
str(dtTidy)
```  

## Tidy Vars
```{r}
key(dtTidy)
```  

## data.table head and tail call
```{r}
dtTidy
```  
",foo)
close(foo)
knit2html('CodeBook.md')
browseURL('CodeBook.html')
